# Generated by Django 4.1 on 2023-12-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventiGroupPlages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('plaging_date', models.DateTimeField(auto_now_add=True)),
                ('plage_payment_status', models.BooleanField(default=False)),
                ('plage_paid_amount', models.IntegerField(default=0)),
                ('plaging_expiry', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi_group.eventigroup')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_plages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
    ]
