# Generated by Django 4.1 on 2023-12-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0002_eventigroupplages'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventigroupplages',
            name='plaged_amount',
            field=models.IntegerField(default=0),
        ),
    ]
