# Generated by Django 4.1 on 2023-12-18 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi_group', '0004_alter_eventigroupplages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventigroupplages',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_plages', to=settings.AUTH_USER_MODEL),
        ),
    ]
