# Generated by Django 4.1 on 2023-12-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0005_alter_eventigroupplages_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventiGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Eventi Group Members',
                'verbose_name_plural': 'Eventi Group Members',
            },
        ),
        migrations.CreateModel(
            name='EventiGroupPlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaging_date', models.DateTimeField(auto_now_add=True)),
                ('plaged_amount', models.IntegerField(default=0)),
                ('plage_payment_status', models.BooleanField(default=False)),
                ('plage_paid_amount', models.IntegerField(default=0)),
                ('plaging_expiry', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Eventi Group Plages',
                'verbose_name_plural': 'Eventi Group Plages',
            },
        ),
        migrations.RemoveField(
            model_name='eventigroup',
            name='members',
        ),
        migrations.DeleteModel(
            name='EventiGroupPlages',
        ),
        migrations.AddField(
            model_name='EventiGroupMembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_instance', to='eventi_group.eventigroup'),
        ),
        migrations.AddField(
            model_name='EventiGroupMembership',
            name='plage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_plage', to='eventi_group.eventigroupplage'),
        ),
    ]
