# Generated by Django 4.1 on 2023-12-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0008_remove_eventigroupmembership_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventiGroupMembership',
        ),
    ]
