# Generated by Django 4.1 on 2023-12-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi_group', '0009_delete_eventigroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('plage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_plage', to='eventi_group.eventigroupplage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eventi Group Members',
                'verbose_name_plural': 'Eventi Group Members',
                'db_table': 'eventi_group_membership',
            },
        ),
    ]
