# Generated by Django 4.1 on 2023-12-26 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi_group', '0011_remove_eventigroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventigroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
