# Generated by Django 4.1 on 2023-12-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0012_eventigroup_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventigroup',
            options={'verbose_name': 'Eventi Group', 'verbose_name_plural': 'Eventi Groups'},
        ),
        migrations.AlterModelTable(
            name='eventigroup',
            table='EVT_group',
        ),
        migrations.AlterModelTable(
            name='eventigroupplage',
            table='EVT_group_plages',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='EVT_group_membership',
        ),
    ]
