# Generated by Django 4.1 on 2023-12-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0015_remove_eventigroup_members_remove_membership_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventigroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
