# Generated by Django 4.1 on 2023-12-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0018_alter_membership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Eventi Group Membership', 'verbose_name_plural': 'Eventi Group Membership'},
        ),
    ]
