# Generated by Django 4.1 on 2023-12-26 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventi_group', '0019_alter_membership_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventigroupplage',
            name='id',
        ),
        migrations.AddField(
            model_name='eventigroupplage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_plage', to='eventi_group.eventigroup'),
        ),
        migrations.AddField(
            model_name='eventigroupplage',
            name='plaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaged_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventigroupplage',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
