# Generated by Django 4.1 on 2023-12-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0020_remove_eventigroupplage_id_eventigroupplage_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberShip',
        ),
    ]
