# Generated by Django 4.1 on 2023-12-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_group', '0021_delete_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventigroupplage',
            old_name='plage_payment_status',
            new_name='paid',
        ),
    ]
